name: Release Artifacts

on:
  push:
    tags:
      - 'v*.*.*'  # e.g. v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          # Your build steps here
          make build
          # Suppose the build output is in dist/ folder
          tar -czf my-artifact.tar.gz dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # The tag that triggered this workflow
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./my-artifact.tar.gz
          asset_name: my-artifact.tar.gz
          asset_content_type: application/gzip
